swagger: "2.0"
info:
  title: "Dynamic Gateway"
  description: "API Gateway for Bilabonnement.dk"
  version: "1.0.0"

tags:
  - name: "Authentication"
    description: "Endpoints for user authentication"
  - name: "CarManagementService API"
    description: "Endpoints related to car management"
  - name: "RentalService API"
    description: "Endpoints related to rentals"
  - name: "CustomerService API"
    description: "Endpoints related to customer data"

paths:
  /login:
    post:
      tags:
        - "Authentication"
      summary: "User Login"
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
                example: "testuser"
              password:
                type: string
                example: "password123"
      responses:
        200:
          description: "Login successful"
        401:
          description: "Unauthorized"
  /register:
    post:
      tags:
        - "Authentication"
      summary: "Register new user"
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
                example: "newuser"
              email:
                type: string
                example: "newuser@example.com"
              password:
                type: string
                example: "securepassword"
      responses:
        201:
          description: "User registered successfully"
        400:
          description: "Bad request"