# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - group-h-api-gateway

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_d1b743e2b7f1441aa1ff89a9f6a1b6a1 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_edf37b86b977479e8fab4d971b3830c4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d1b743e2b7f1441aa1ff89a9f6a1b6a1 }}/apigateway:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'group-h-api-gateway'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e28faf89cd6c44bf976eeaf6ca67d4ec }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d1b743e2b7f1441aa1ff89a9f6a1b6a1 }}/apigateway:${{ github.sha }}'